language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux
#before_install:
#- ./bootstrap.sh
script:
- ./bootstrap.sh; cd scripts; ./build_all.sh; ./run_tests.sh
env:
  global:
  - LANG="en_US.UTF-8"

#######################
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          compiler: gcc
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - g++-8
          env: COMPILER=g++-8

